### ISSUE TITLE
license clarification

### ISSUE THREAD

**Issue by yysizif** [AlexanderSobolev1990/espd_gost_19_kit#1]
Alexander, thank you for your excellent work.  I am eager to get rid of the old Word workflow and stick with Latex from now on, but could you please clarify what you meant by releasing it under GPL? Will the documentation we write in this framework count as a derived work so we have to release the doc sources under GPL?  Or you meant any framework fixes or extensions we might make need to be published, but the docs produced with it can stay private?  I hope the latter is true, but please clarify to be sure.

Спасибо,

-- Юрий

**Comment by AlexanderSobolev1990** [comment]
Hi, yysizif.

License updated to LGPL 3.0, so use my code as you want - may the force of freedom be with you.

--
Alex

**Comment by AlexanderSobolev1990** [comment]
Hi, yysizif.

License updated to LGPL 3.0, so use my code as you want - may the force of
freedom be with you.

--
Alex

вт, 29 авг. 2023 г., 08:31 yysizif ***@***.***>:

**Comment by yysizif** [comment]
Thanks a lot, and the best of luck to you!  Nice normocontrollers and all such)
